-- 0001_identity_profiles
-- Phase 01 — Identity & Profiles. Design: docs/data/IDENTITY_DATA_MODEL.md.
--
-- Separation of concerns (three aggregates, never merged):
--   ACCOUNT          account, account_role, consent_record, account_deletion_request, data_export_request
--   AUTHENTICATION   account_credential, account_identity, verification_code, auth_session, device, identity_audit_ledger
--   PUBLIC PROFILE   profile, interest, account_interest, privacy_settings, account_block
--
-- Identity key: account.id (UUID v7, generated by the application, immutable). Email and username
-- are mutable attributes with partial unique indexes — never foreign keys, never identity.
--
-- Query patterns behind each index are noted inline. All FKs are indexed. ON DELETE is RESTRICT
-- everywhere except inside the account aggregate, where rows are erased by the deletion job
-- (application-level cascade so every step is audited), not by the database.
--
-- Rollback (reverse order; data loss is inherent — run only before any production traffic):
--   DROP TABLE account_block, privacy_settings, account_interest, interest, profile,
--              identity_audit_ledger, data_export_request, account_deletion_request, consent_record,
--              account_role, device, auth_session, verification_code, account_identity,
--              account_credential, account;

-- ============================================================================================
-- ACCOUNT
-- ============================================================================================

CREATE TABLE account (
  id                       uuid PRIMARY KEY,
  -- CONFIDENTIAL. Lower-cased by the application; uniqueness is case-insensitive and applies to
  -- live accounts only (deleted accounts keep a tombstone hash so the address can be reused).
  email                    text,
  email_verified_at        timestamptz,
  -- sha256(email) retained after deletion for abuse/fraud correlation; never reversible.
  email_tombstone          text,
  state                    text NOT NULL,
  -- CONFIDENTIAL. Used only to derive the age band; never returned to clients or other users.
  date_of_birth            date NOT NULL,
  last_login_at            timestamptz,
  deactivated_at           timestamptz,
  suspended_at             timestamptz,
  suspended_by             uuid,
  -- Internal, staff-only text. Never shown to the user.
  suspension_reason        text,
  deleted_at               timestamptz,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT account_state_check CHECK (
    state IN ('PENDING_VERIFICATION','ACTIVE','DEACTIVATED','SUSPENDED','DELETION_REQUESTED','DELETED')
  ),
  -- A live account always has an email; a deleted one never does.
  CONSTRAINT account_email_lifecycle_check CHECK (
    (state = 'DELETED' AND email IS NULL AND email_tombstone IS NOT NULL)
    OR (state <> 'DELETED' AND email IS NOT NULL)
  ),
  -- ACTIVE implies a verified email (PENDING_VERIFICATION is the only unverified live state).
  CONSTRAINT account_active_verified_check CHECK (state <> 'ACTIVE' OR email_verified_at IS NOT NULL),
  CONSTRAINT account_suspended_by_fk FOREIGN KEY (suspended_by) REFERENCES account (id) ON DELETE RESTRICT
);
--> statement-breakpoint
-- Sign-in / registration lookup; case-insensitive uniqueness among live accounts.
CREATE UNIQUE INDEX account_email_live_uidx ON account (lower(email)) WHERE deleted_at IS NULL;
--> statement-breakpoint
CREATE INDEX account_suspended_by_idx ON account (suspended_by) WHERE suspended_by IS NOT NULL;
--> statement-breakpoint
CREATE TRIGGER account_set_updated_at BEFORE UPDATE ON account
  FOR EACH ROW EXECUTE FUNCTION quest_set_updated_at();
--> statement-breakpoint

-- Staff roles ledger. USER is implicit and never stored. Revoked grants are kept for audit.
CREATE TABLE account_role (
  id          uuid PRIMARY KEY,
  account_id  uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  role        text NOT NULL,
  granted_by  uuid REFERENCES account (id) ON DELETE RESTRICT,
  granted_at  timestamptz NOT NULL DEFAULT now(),
  revoked_by  uuid REFERENCES account (id) ON DELETE RESTRICT,
  revoked_at  timestamptz,
  CONSTRAINT account_role_role_check CHECK (
    role IN ('SUPER_ADMIN','TRUST_SAFETY_LEAD','MODERATOR','SUPPORT','ANALYST','READ_ONLY')
  )
);
--> statement-breakpoint
-- One active grant per (account, role); history rows are those with revoked_at set.
CREATE UNIQUE INDEX account_role_active_uidx ON account_role (account_id, role) WHERE revoked_at IS NULL;
--> statement-breakpoint
CREATE INDEX account_role_account_idx ON account_role (account_id);
--> statement-breakpoint
CREATE INDEX account_role_granted_by_idx ON account_role (granted_by) WHERE granted_by IS NOT NULL;
--> statement-breakpoint
CREATE INDEX account_role_revoked_by_idx ON account_role (revoked_by) WHERE revoked_by IS NOT NULL;
--> statement-breakpoint

-- Append-only consent ledger (never updated, never deleted while the account lives; anonymised
-- with the account — the fact that consent existed is retained under legal basis).
CREATE TABLE consent_record (
  id                uuid PRIMARY KEY,
  account_id        uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  consent_type      text NOT NULL,
  document_version  text,
  granted           boolean NOT NULL,
  source            text NOT NULL,
  recorded_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT consent_record_type_check CHECK (
    consent_type IN ('TERMS_OF_SERVICE','PRIVACY_POLICY','AGE_ATTESTATION','ANALYTICS','PERSONALISATION','MARKETING')
  ),
  CONSTRAINT consent_record_source_check CHECK (source IN ('REGISTRATION','SETTINGS','REPROMPT','SUPPORT'))
);
--> statement-breakpoint
-- Consent state/history: newest first within an account (id DESC tiebreak — UUID v7 is time-ordered).
CREATE INDEX consent_record_account_recorded_idx ON consent_record (account_id, recorded_at DESC, id DESC);
--> statement-breakpoint

CREATE TABLE account_deletion_request (
  id             uuid PRIMARY KEY,
  account_id     uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  status         text NOT NULL,
  -- State the account was in when the request was made; restored on cancel.
  previous_state text NOT NULL,
  reason         text,
  requested_at   timestamptz NOT NULL DEFAULT now(),
  scheduled_for  timestamptz NOT NULL,
  cancelled_at   timestamptz,
  completed_at   timestamptz,
  CONSTRAINT account_deletion_request_status_check CHECK (status IN ('PENDING','CANCELLED','COMPLETED')),
  CONSTRAINT account_deletion_request_previous_state_check CHECK (
    previous_state IN ('PENDING_VERIFICATION','ACTIVE','DEACTIVATED','SUSPENDED')
  )
);
--> statement-breakpoint
-- At most one pending request per account.
CREATE UNIQUE INDEX account_deletion_request_pending_uidx ON account_deletion_request (account_id) WHERE status = 'PENDING';
--> statement-breakpoint
CREATE INDEX account_deletion_request_account_idx ON account_deletion_request (account_id);
--> statement-breakpoint
-- Deletion job: due pending requests.
CREATE INDEX account_deletion_request_due_idx ON account_deletion_request (scheduled_for) WHERE status = 'PENDING';
--> statement-breakpoint

CREATE TABLE data_export_request (
  id              uuid PRIMARY KEY,
  account_id      uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  status          text NOT NULL,
  requested_at    timestamptz NOT NULL DEFAULT now(),
  started_at      timestamptz,
  completed_at    timestamptz,
  expires_at      timestamptz,
  -- Object key of the generated bundle; the object itself expires with the storage lifecycle rule.
  object_key      text,
  failure_reason  text,
  CONSTRAINT data_export_request_status_check CHECK (
    status IN ('REQUESTED','PROCESSING','READY','EXPIRED','FAILED')
  )
);
--> statement-breakpoint
CREATE INDEX data_export_request_account_idx ON data_export_request (account_id, requested_at DESC);
--> statement-breakpoint
-- Export worker: open work items in order.
CREATE INDEX data_export_request_open_idx ON data_export_request (requested_at) WHERE status IN ('REQUESTED','PROCESSING');
--> statement-breakpoint

-- ============================================================================================
-- AUTHENTICATION
-- ============================================================================================

-- Password credential (one per account; absent for provider-only accounts).
CREATE TABLE account_credential (
  account_id            uuid PRIMARY KEY REFERENCES account (id) ON DELETE RESTRICT,
  -- PHC string ($argon2id$...). Algorithm parameters travel inside the hash for rehash-on-login.
  password_hash         text NOT NULL,
  password_changed_at   timestamptz NOT NULL DEFAULT now(),
  -- Brute-force protection: consecutive failures and temporary lock (see IDENTITY_THREAT_MODEL.md).
  failed_attempts       integer NOT NULL DEFAULT 0,
  locked_until          timestamptz,
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT account_credential_failed_attempts_check CHECK (failed_attempts >= 0)
);
--> statement-breakpoint
CREATE TRIGGER account_credential_set_updated_at BEFORE UPDATE ON account_credential
  FOR EACH ROW EXECUTE FUNCTION quest_set_updated_at();
--> statement-breakpoint

-- External identity links (Apple / Google / FAKE for local). The provider subject is the only
-- stable key the provider guarantees; the email at link time is informational.
CREATE TABLE account_identity (
  id                 uuid PRIMARY KEY,
  account_id         uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  provider           text NOT NULL,
  provider_subject   text NOT NULL,
  email_at_link      text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  last_used_at       timestamptz,
  CONSTRAINT account_identity_provider_check CHECK (provider IN ('APPLE','GOOGLE','FAKE')),
  CONSTRAINT account_identity_provider_subject_uidx UNIQUE (provider, provider_subject)
);
--> statement-breakpoint
CREATE INDEX account_identity_account_idx ON account_identity (account_id);
--> statement-breakpoint

-- One-time codes (email verification, password reset). Only the hash is stored.
CREATE TABLE verification_code (
  id           uuid PRIMARY KEY,
  account_id   uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  purpose      text NOT NULL,
  code_hash    text NOT NULL,
  expires_at   timestamptz NOT NULL,
  attempts     integer NOT NULL DEFAULT 0,
  consumed_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT verification_code_purpose_check CHECK (purpose IN ('VERIFY_EMAIL','RESET_PASSWORD')),
  CONSTRAINT verification_code_attempts_check CHECK (attempts >= 0)
);
--> statement-breakpoint
-- At most one live code per account/purpose (issuing consumes the previous one in the same tx).
CREATE UNIQUE INDEX verification_code_live_uidx ON verification_code (account_id, purpose) WHERE consumed_at IS NULL;
--> statement-breakpoint
CREATE INDEX verification_code_account_idx ON verification_code (account_id, created_at DESC);
--> statement-breakpoint

-- Registered client installations (for sessions display now, push notifications later).
CREATE TABLE device (
  id               uuid PRIMARY KEY,
  account_id       uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  installation_id  text NOT NULL,
  platform         text NOT NULL,
  app_version      text,
  device_name      text,
  -- CONFIDENTIAL. Never returned by the API; cleared on revoke.
  push_token       text,
  locale           text,
  timezone         text,
  last_seen_at     timestamptz NOT NULL DEFAULT now(),
  revoked_at       timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT device_platform_check CHECK (platform IN ('IOS','ANDROID','WEB')),
  CONSTRAINT device_account_installation_uidx UNIQUE (account_id, installation_id)
);
--> statement-breakpoint
CREATE INDEX device_account_idx ON device (account_id) WHERE revoked_at IS NULL;
--> statement-breakpoint
CREATE TRIGGER device_set_updated_at BEFORE UPDATE ON device
  FOR EACH ROW EXECUTE FUNCTION quest_set_updated_at();
--> statement-breakpoint

-- Refresh-token sessions. The token itself is never stored: only sha256(token). Rotation bumps
-- refresh_generation; presenting a token from an older generation = reuse → whole session revoked.
CREATE TABLE auth_session (
  id                    uuid PRIMARY KEY,
  account_id            uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  device_id             uuid REFERENCES device (id) ON DELETE RESTRICT,
  refresh_token_hash    text NOT NULL,
  -- Hash of the token that was just rotated out: presenting it again is a reuse (theft) signal.
  previous_refresh_token_hash text,
  refresh_generation    integer NOT NULL DEFAULT 1,
  refresh_expires_at    timestamptz NOT NULL,
  absolute_expires_at   timestamptz NOT NULL,
  client_platform       text,
  client_app_version    text,
  client_device_name    text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  last_used_at          timestamptz NOT NULL DEFAULT now(),
  revoked_at            timestamptz,
  revoked_reason        text,
  CONSTRAINT auth_session_refresh_token_hash_uidx UNIQUE (refresh_token_hash),
  CONSTRAINT auth_session_platform_check CHECK (client_platform IS NULL OR client_platform IN ('IOS','ANDROID','WEB'))
);
--> statement-breakpoint
-- Sessions list + "revoke all" for an account.
CREATE INDEX auth_session_account_live_idx ON auth_session (account_id, created_at DESC) WHERE revoked_at IS NULL;
--> statement-breakpoint
CREATE INDEX auth_session_previous_hash_idx ON auth_session (previous_refresh_token_hash) WHERE previous_refresh_token_hash IS NOT NULL;
--> statement-breakpoint
CREATE INDEX auth_session_device_idx ON auth_session (device_id) WHERE device_id IS NOT NULL;
--> statement-breakpoint
-- Retention job: expired sessions are hard-deleted after 90 days.
CREATE INDEX auth_session_absolute_expires_idx ON auth_session (absolute_expires_at);
--> statement-breakpoint

-- Security-relevant events (sign-in outcomes, revocations, role changes). No PII beyond ids;
-- metadata is a flat JSON object of low-cardinality strings.
CREATE TABLE identity_audit_ledger (
  id           uuid PRIMARY KEY,
  account_id   uuid REFERENCES account (id) ON DELETE RESTRICT,
  actor_id     uuid REFERENCES account (id) ON DELETE RESTRICT,
  event_type   text NOT NULL,
  session_id   uuid,
  metadata     jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at  timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX identity_audit_ledger_account_idx ON identity_audit_ledger (account_id, occurred_at DESC) WHERE account_id IS NOT NULL;
--> statement-breakpoint
CREATE INDEX identity_audit_ledger_actor_idx ON identity_audit_ledger (actor_id) WHERE actor_id IS NOT NULL;
--> statement-breakpoint
CREATE INDEX identity_audit_ledger_type_time_idx ON identity_audit_ledger (event_type, occurred_at DESC);
--> statement-breakpoint

-- ============================================================================================
-- PUBLIC PROFILE
-- ============================================================================================

CREATE TABLE profile (
  account_id         uuid PRIMARY KEY REFERENCES account (id) ON DELETE RESTRICT,
  -- Mutable public handle, lower-case, unique among live profiles. Not an identity key.
  username           text,
  display_name       text,
  bio                text NOT NULL DEFAULT '',
  avatar_object_key  text,
  language           text NOT NULL DEFAULT 'en',
  country            text,
  timezone           text,
  -- Mirrors the account lifecycle (maintained by the Identity context through the provisioning
  -- port in the same transaction): only ACTIVE accounts are visible to other users.
  account_active     boolean NOT NULL DEFAULT false,
  onboarding_completed_at timestamptz,
  erased_at          timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profile_username_format_check CHECK (username IS NULL OR username ~ '^[a-z][a-z0-9_]{2,29}$'),
  CONSTRAINT profile_country_format_check CHECK (country IS NULL OR country ~ '^[A-Z]{2}$')
);
--> statement-breakpoint
CREATE UNIQUE INDEX profile_username_uidx ON profile (username) WHERE username IS NOT NULL;
--> statement-breakpoint
CREATE TRIGGER profile_set_updated_at BEFORE UPDATE ON profile
  FOR EACH ROW EXECUTE FUNCTION quest_set_updated_at();
--> statement-breakpoint

-- Interest catalogue (operator-managed reference data; labels localised in a later phase).
CREATE TABLE interest (
  key         text PRIMARY KEY,
  label       text NOT NULL,
  category    text NOT NULL,
  sort_order  integer NOT NULL,
  active      boolean NOT NULL DEFAULT true,
  CONSTRAINT interest_key_format_check CHECK (key ~ '^[a-z][a-z0-9-]{1,39}$')
);
--> statement-breakpoint
CREATE INDEX interest_active_sort_idx ON interest (category, sort_order) WHERE active;
--> statement-breakpoint

CREATE TABLE account_interest (
  account_id    uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  interest_key  text NOT NULL REFERENCES interest (key) ON DELETE RESTRICT,
  selected_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (account_id, interest_key)
);
--> statement-breakpoint
CREATE INDEX account_interest_interest_idx ON account_interest (interest_key);
--> statement-breakpoint

CREATE TABLE privacy_settings (
  account_id             uuid PRIMARY KEY REFERENCES account (id) ON DELETE RESTRICT,
  profile_visibility     text NOT NULL,
  location_visibility    text NOT NULL,
  challenge_invites_from text NOT NULL,
  discoverable           boolean NOT NULL,
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT privacy_settings_profile_visibility_check CHECK (profile_visibility IN ('PUBLIC','FOLLOWERS','PRIVATE')),
  -- PRECISE is deliberately not a value: precise location is never shown to other users.
  CONSTRAINT privacy_settings_location_visibility_check CHECK (location_visibility IN ('HIDDEN','CITY','NEIGHBOURHOOD')),
  CONSTRAINT privacy_settings_challenge_invites_check CHECK (challenge_invites_from IN ('EVERYONE','FOLLOWERS','NOBODY'))
);
--> statement-breakpoint
CREATE TRIGGER privacy_settings_set_updated_at BEFORE UPDATE ON privacy_settings
  FOR EACH ROW EXECUTE FUNCTION quest_set_updated_at();
--> statement-breakpoint

-- Blocks: precedence over every other relationship (PRIVACY_PRINCIPLES §7). The social graph
-- (Phase 03) reads them through the BlockQueryPort; it never owns them.
CREATE TABLE account_block (
  blocker_account_id  uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  blocked_account_id  uuid NOT NULL REFERENCES account (id) ON DELETE RESTRICT,
  created_at          timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_account_id, blocked_account_id),
  CONSTRAINT account_block_not_self_check CHECK (blocker_account_id <> blocked_account_id)
);
--> statement-breakpoint
-- "Who blocked me" lookups (visibility checks in both directions).
CREATE INDEX account_block_blocked_idx ON account_block (blocked_account_id);
--> statement-breakpoint

-- ============================================================================================
-- Reference data: initial interest catalogue (idempotent).
-- ============================================================================================
INSERT INTO interest (key, label, category, sort_order) VALUES
  ('fitness',            'Fitness & workouts',        'body',       10),
  ('running',            'Running',                   'body',       20),
  ('cycling',            'Cycling',                   'body',       30),
  ('hiking',             'Hiking & trails',           'outdoors',   40),
  ('camping',            'Camping',                   'outdoors',   50),
  ('urban-exploration',  'Urban exploration',         'outdoors',   60),
  ('photography',        'Photography',               'creative',   70),
  ('art',                'Art & drawing',             'creative',   80),
  ('music',              'Music',                     'creative',   90),
  ('writing',            'Writing & journaling',      'creative',  100),
  ('cooking',            'Cooking',                   'home',      110),
  ('gardening',          'Gardening',                 'home',      120),
  ('diy',                'DIY & making',              'home',      130),
  ('volunteering',       'Volunteering',              'community', 140),
  ('sustainability',     'Sustainability & cleanups', 'community', 150),
  ('local-business',     'Supporting local business', 'community', 160),
  ('learning',           'Learning new skills',       'growth',    170),
  ('reading',            'Reading',                   'growth',    180),
  ('languages',          'Languages',                 'growth',    190),
  ('mindfulness',        'Mindfulness',               'wellbeing', 200),
  ('sleep-habits',       'Sleep & habits',            'wellbeing', 210),
  ('travel',             'Travel & discovery',        'discovery', 220),
  ('food-discovery',     'Food discovery',            'discovery', 230),
  ('culture-heritage',   'Culture & heritage',        'discovery', 240),
  ('team-sports',        'Team sports',               'social',    250),
  ('family',             'Family activities',         'social',    260)
ON CONFLICT (key) DO NOTHING;
