import { AsyncLocalStorage } from 'node:async_hooks';
import { randomUUID } from 'node:crypto';

export const CORRELATION_ID_HEADER = 'x-correlation-id';
export const REQUEST_ID_HEADER = 'x-request-id';

/** Correlation ids are client-suppliable but constrained to a safe charset/length. */
const SAFE_ID = /^[A-Za-z0-9._:-]{8,128}$/;

export interface RequestContext {
  /** Unique per HTTP request; generated by the server. */
  requestId: string;
  /** Spans a whole user journey across requests/events; accepted from the client if well-formed. */
  correlationId: string;
  /** Acting principal id, set by authentication in Phase 01. Never an email or name. */
  actorId?: string;
  startedAt: number;
}

const storage = new AsyncLocalStorage<RequestContext>();

export function sanitizeIncomingId(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  return SAFE_ID.test(value) ? value : undefined;
}

export function createRequestContext(incomingCorrelationId?: unknown): RequestContext {
  const requestId = randomUUID();
  return {
    requestId,
    correlationId: sanitizeIncomingId(incomingCorrelationId) ?? requestId,
    startedAt: Date.now(),
  };
}

export function runWithRequestContext<T>(ctx: RequestContext, fn: () => T): T {
  return storage.run(ctx, fn);
}

/** Current context, or undefined outside a request (workers, scripts, tests). */
export function getRequestContext(): RequestContext | undefined {
  return storage.getStore();
}

export function getCorrelationId(): string {
  return storage.getStore()?.correlationId ?? 'no-request-context';
}
