import {
  type Permission,
  acceptedResponseSchema,
  accountSupportViewSchema,
  accountViewSchema,
  authResponseSchema,
  avatarUploadRequestSchema,
  avatarUploadResponseSchema,
  blockListSchema,
  blockUserRequestSchema,
  changePasswordRequestSchema,
  consentHistorySchema,
  consentStateSchema,
  dataExportRequestViewSchema,
  deletionRequestViewSchema,
  deviceListSchema,
  deviceViewSchema,
  forgotPasswordRequestSchema,
  grantRoleRequestSchema,
  interestCatalogueSchema,
  interestsViewSchema,
  livenessResponseSchema,
  loginRequestSchema,
  onboardingStatusSchema,
  ownProfileViewSchema,
  privacySettingsSchema,
  providerRegisterRequestSchema,
  providerSignInRequestSchema,
  publicProfileViewSchema,
  readinessResponseSchema,
  recordConsentRequestSchema,
  refreshRequestSchema,
  registerDeviceRequestSchema,
  registerRequestSchema,
  requestDeletionRequestSchema,
  resetPasswordRequestSchema,
  revokeRoleRequestSchema,
  sessionListSchema,
  acceptQuestRequestSchema,
  archiveQuestRequestSchema,
  completionRequestSchema,
  createQuestRequestSchema,
  participationListSchema,
  participationViewSchema,
  publishQuestRequestSchema,
  questAssessmentViewSchema,
  questCategoryListSchema,
  questDetailSchema,
  questListQuerySchema,
  questListSchema,
  questSupportViewSchema,
  suspendAccountRequestSchema,
  suspendQuestRequestSchema,
  updateInterestsRequestSchema,
  updatePrivacySettingsRequestSchema,
  updateProfileRequestSchema,
  updateQuestRequestSchema,
  usernameAvailabilityResponseSchema,
  verifyEmailRequestSchema,
} from '@quest/types';

import { listPageQuerySchema } from '../common/pagination/cursor-page';
import { z } from 'zod';

/**
 * Route registry — the single source for the generated OpenAPI document (ADR-012). Every HTTP
 * route the application registers must appear here (verified by src/openapi/openapi.test.ts),
 * so the contract cannot drift from the implementation silently.
 */
export interface RouteDescriptor {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  /** Express-style path as registered (e.g. /v1/me/sessions/:sessionId). */
  path: string;
  tag: string;
  summary: string;
  /** `public` = no token; otherwise the permission(s) required (empty = any authenticated user). */
  auth: 'public' | Permission[];
  states?: string[];
  requiresVerifiedEmail?: boolean;
  request?: z.ZodTypeAny;
  query?: z.ZodTypeAny;
  responses: Record<number, z.ZodTypeAny | null>;
  /** Per-route rate limit (requests per window) when stricter than the global default. */
  rateLimit?: { limit: number; windowSeconds: number };
}

const systemInfoSchema = z.object({
  service: z.string(),
  version: z.string(),
  commit: z.string(),
  environment: z.string(),
  apiVersion: z.string(),
});
const revokedSessionsSchema = z.object({ revokedSessions: z.number().int() });
const availabilityQuerySchema = z.object({ username: z.string().min(1).max(64) });

const ANY_USER: Permission[] = [];
const GRACE = ['ACTIVE', 'PENDING_VERIFICATION', 'DELETION_REQUESTED'];

export const ROUTES: ReadonlyArray<RouteDescriptor> = [
  // ---- platform ----
  {
    method: 'GET',
    path: '/health',
    tag: 'platform',
    summary: 'Liveness',
    auth: 'public',
    responses: { 200: livenessResponseSchema },
  },
  {
    method: 'GET',
    path: '/ready',
    tag: 'platform',
    summary: 'Readiness',
    auth: 'public',
    responses: { 200: readinessResponseSchema, 503: readinessResponseSchema },
  },
  {
    method: 'GET',
    path: '/v1/system/info',
    tag: 'platform',
    summary: 'Build information',
    auth: 'public',
    responses: { 200: systemInfoSchema },
  },

  // ---- authentication ----
  {
    method: 'POST',
    path: '/v1/auth/register',
    tag: 'auth',
    summary: 'Register with email and password',
    auth: 'public',
    request: registerRequestSchema,
    responses: { 201: authResponseSchema, 400: null, 403: null, 409: null },
    rateLimit: { limit: 5, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/login',
    tag: 'auth',
    summary: 'Sign in with email and password',
    auth: 'public',
    request: loginRequestSchema,
    responses: { 200: authResponseSchema, 401: null },
    rateLimit: { limit: 10, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/provider/sign-in',
    tag: 'auth',
    summary: 'Sign in with an external identity (Apple/Google)',
    auth: 'public',
    request: providerSignInRequestSchema,
    responses: { 200: authResponseSchema, 401: null, 404: null },
    rateLimit: { limit: 10, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/provider/register',
    tag: 'auth',
    summary: 'Register with an external identity',
    auth: 'public',
    request: providerRegisterRequestSchema,
    responses: { 201: authResponseSchema, 400: null, 401: null, 403: null, 409: null },
    rateLimit: { limit: 5, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/refresh',
    tag: 'auth',
    summary: 'Rotate the refresh token and issue a new access token',
    auth: 'public',
    request: refreshRequestSchema,
    responses: { 200: authResponseSchema, 401: null },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/logout',
    tag: 'auth',
    summary: 'Sign out the current session',
    auth: ANY_USER,
    states: GRACE,
    responses: { 204: null },
  },
  {
    method: 'POST',
    path: '/v1/auth/logout-all',
    tag: 'auth',
    summary: 'Sign out everywhere',
    auth: ANY_USER,
    states: GRACE,
    responses: { 200: revokedSessionsSchema },
  },
  {
    method: 'POST',
    path: '/v1/auth/email/verify',
    tag: 'auth',
    summary: 'Verify the email address with the mailed code',
    auth: ANY_USER,
    request: verifyEmailRequestSchema,
    responses: { 200: accountViewSchema, 400: null },
    rateLimit: { limit: 10, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/email/resend',
    tag: 'auth',
    summary: 'Resend the verification code',
    auth: ANY_USER,
    responses: { 202: acceptedResponseSchema, 409: null },
    rateLimit: { limit: 3, windowSeconds: 300 },
  },
  {
    method: 'POST',
    path: '/v1/auth/password/change',
    tag: 'auth',
    summary: 'Change password (revokes other sessions)',
    auth: ANY_USER,
    request: changePasswordRequestSchema,
    responses: { 204: null, 401: null },
    rateLimit: { limit: 5, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/auth/password/forgot',
    tag: 'auth',
    summary: 'Request a password-reset code (always 202)',
    auth: 'public',
    request: forgotPasswordRequestSchema,
    responses: { 202: acceptedResponseSchema },
    rateLimit: { limit: 3, windowSeconds: 300 },
  },
  {
    method: 'POST',
    path: '/v1/auth/password/reset',
    tag: 'auth',
    summary: 'Reset the password with the mailed code',
    auth: 'public',
    request: resetPasswordRequestSchema,
    responses: { 204: null, 400: null },
    rateLimit: { limit: 5, windowSeconds: 60 },
  },

  // ---- account (me) ----
  {
    method: 'GET',
    path: '/v1/me',
    tag: 'account',
    summary: 'The signed-in account',
    auth: ANY_USER,
    states: GRACE,
    responses: { 200: accountViewSchema },
  },
  {
    method: 'GET',
    path: '/v1/me/sessions',
    tag: 'account',
    summary: 'List live sessions',
    auth: ['MANAGE_OWN_SESSIONS'],
    responses: { 200: sessionListSchema },
  },
  {
    method: 'DELETE',
    path: '/v1/me/sessions/:sessionId',
    tag: 'account',
    summary: 'Revoke a session',
    auth: ['MANAGE_OWN_SESSIONS'],
    responses: { 204: null },
  },
  {
    method: 'GET',
    path: '/v1/me/devices',
    tag: 'account',
    summary: 'List registered devices',
    auth: ['MANAGE_OWN_DEVICES'],
    responses: { 200: deviceListSchema },
  },
  {
    method: 'POST',
    path: '/v1/me/devices',
    tag: 'account',
    summary: 'Register or update a device (push token never returned)',
    auth: ['MANAGE_OWN_DEVICES'],
    request: registerDeviceRequestSchema,
    responses: { 200: deviceViewSchema },
    rateLimit: { limit: 20, windowSeconds: 60 },
  },
  {
    method: 'DELETE',
    path: '/v1/me/devices/:deviceId',
    tag: 'account',
    summary: 'Revoke a device',
    auth: ['MANAGE_OWN_DEVICES'],
    responses: { 204: null, 404: null },
  },
  {
    method: 'GET',
    path: '/v1/me/consents',
    tag: 'account',
    summary: 'Current consent state',
    auth: ['MANAGE_OWN_ACCOUNT'],
    states: GRACE,
    responses: { 200: consentStateSchema },
  },
  {
    method: 'GET',
    path: '/v1/me/consents/history',
    tag: 'account',
    summary: 'Consent history (append-only, keyset-paged)',
    auth: ['MANAGE_OWN_ACCOUNT'],
    states: GRACE,
    query: listPageQuerySchema,
    responses: { 200: consentHistorySchema },
  },
  {
    method: 'POST',
    path: '/v1/me/consents',
    tag: 'account',
    summary: 'Record a consent decision',
    auth: ['MANAGE_OWN_ACCOUNT'],
    request: recordConsentRequestSchema,
    responses: { 200: consentStateSchema, 400: null },
  },
  {
    method: 'POST',
    path: '/v1/me/deactivate',
    tag: 'account',
    summary: 'Deactivate the account (sign-in reactivates)',
    auth: ['MANAGE_OWN_ACCOUNT'],
    states: ['ACTIVE'],
    responses: { 204: null, 409: null },
  },
  {
    method: 'POST',
    path: '/v1/me/deletion-request',
    tag: 'account',
    summary: 'Request account deletion (30-day grace)',
    auth: ['REQUEST_OWN_DELETION'],
    request: requestDeletionRequestSchema,
    responses: { 201: deletionRequestViewSchema, 401: null, 409: null },
    rateLimit: { limit: 3, windowSeconds: 300 },
  },
  {
    method: 'GET',
    path: '/v1/me/deletion-request',
    tag: 'account',
    summary: 'Latest deletion request',
    auth: ['REQUEST_OWN_DELETION'],
    states: GRACE,
    responses: { 200: deletionRequestViewSchema, 404: null },
  },
  {
    method: 'POST',
    path: '/v1/me/deletion-request/cancel',
    tag: 'account',
    summary: 'Cancel a pending deletion request',
    auth: ['REQUEST_OWN_DELETION'],
    states: ['DELETION_REQUESTED'],
    responses: { 200: accountViewSchema, 404: null },
  },
  {
    method: 'POST',
    path: '/v1/me/data-export',
    tag: 'account',
    summary: 'Request a user-data export',
    auth: ['REQUEST_OWN_DATA_EXPORT'],
    requiresVerifiedEmail: true,
    responses: { 202: dataExportRequestViewSchema, 409: null },
    rateLimit: { limit: 3, windowSeconds: 300 },
  },
  {
    method: 'GET',
    path: '/v1/me/data-export',
    tag: 'account',
    summary: 'Latest data export',
    auth: ['REQUEST_OWN_DATA_EXPORT'],
    responses: { 200: dataExportRequestViewSchema, 404: null },
  },
  {
    method: 'GET',
    path: '/v1/me/data-export/:exportId',
    tag: 'account',
    summary: 'Data export by id',
    auth: ['REQUEST_OWN_DATA_EXPORT'],
    responses: { 200: dataExportRequestViewSchema, 404: null },
  },

  // ---- profile (me) ----
  {
    method: 'GET',
    path: '/v1/me/profile',
    tag: 'profile',
    summary: 'Own profile',
    auth: ['MANAGE_OWN_PROFILE'],
    responses: { 200: ownProfileViewSchema },
  },
  {
    method: 'PUT',
    path: '/v1/me/profile',
    tag: 'profile',
    summary: 'Update own profile (partial)',
    auth: ['MANAGE_OWN_PROFILE'],
    request: updateProfileRequestSchema,
    responses: { 200: ownProfileViewSchema, 400: null, 403: null, 409: null },
  },
  {
    method: 'POST',
    path: '/v1/me/profile/avatar-upload',
    tag: 'profile',
    summary: 'Pre-signed avatar upload (direct-to-storage)',
    auth: ['MANAGE_OWN_PROFILE'],
    requiresVerifiedEmail: true,
    request: avatarUploadRequestSchema,
    responses: { 200: avatarUploadResponseSchema },
    rateLimit: { limit: 10, windowSeconds: 60 },
  },
  {
    method: 'GET',
    path: '/v1/me/interests',
    tag: 'profile',
    summary: 'Selected interests',
    auth: ['MANAGE_OWN_PROFILE'],
    responses: { 200: interestsViewSchema },
  },
  {
    method: 'PUT',
    path: '/v1/me/interests',
    tag: 'profile',
    summary: 'Replace selected interests',
    auth: ['MANAGE_OWN_PROFILE'],
    request: updateInterestsRequestSchema,
    responses: { 200: interestsViewSchema, 400: null },
  },
  {
    method: 'GET',
    path: '/v1/me/onboarding',
    tag: 'profile',
    summary: 'Onboarding status',
    auth: ['MANAGE_OWN_PROFILE'],
    responses: { 200: onboardingStatusSchema },
  },
  {
    method: 'POST',
    path: '/v1/me/onboarding/complete',
    tag: 'profile',
    summary: 'Complete onboarding',
    auth: ['MANAGE_OWN_PROFILE'],
    requiresVerifiedEmail: true,
    responses: { 200: onboardingStatusSchema, 400: null },
  },
  {
    method: 'GET',
    path: '/v1/me/privacy',
    tag: 'privacy',
    summary: 'Privacy settings',
    auth: ['MANAGE_OWN_PRIVACY'],
    responses: { 200: privacySettingsSchema },
  },
  {
    method: 'PUT',
    path: '/v1/me/privacy',
    tag: 'privacy',
    summary: 'Update privacy settings (age policy enforced)',
    auth: ['MANAGE_OWN_PRIVACY'],
    request: updatePrivacySettingsRequestSchema,
    responses: { 200: privacySettingsSchema, 403: null },
  },
  {
    method: 'GET',
    path: '/v1/me/blocks',
    tag: 'privacy',
    summary: 'Blocked accounts',
    auth: ['MANAGE_OWN_BLOCKS'],
    query: listPageQuerySchema,
    responses: { 200: blockListSchema },
  },
  {
    method: 'POST',
    path: '/v1/me/blocks',
    tag: 'privacy',
    summary: 'Block an account',
    auth: ['MANAGE_OWN_BLOCKS'],
    request: blockUserRequestSchema,
    responses: { 204: null, 400: null, 404: null },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'DELETE',
    path: '/v1/me/blocks/:accountId',
    tag: 'privacy',
    summary: 'Unblock an account',
    auth: ['MANAGE_OWN_BLOCKS'],
    responses: { 204: null, 404: null },
  },

  // ---- public ----
  {
    method: 'GET',
    path: '/v1/interests',
    tag: 'public',
    summary: 'Interest catalogue',
    auth: 'public',
    responses: { 200: interestCatalogueSchema },
  },
  {
    method: 'GET',
    path: '/v1/profiles/username-availability',
    tag: 'public',
    summary: 'Username availability',
    auth: 'public',
    query: availabilityQuerySchema,
    responses: { 200: usernameAvailabilityResponseSchema },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'GET',
    path: '/v1/profiles/:username',
    tag: 'public',
    summary: 'Public profile by handle (visibility and blocks applied)',
    auth: 'public',
    responses: { 200: publicProfileViewSchema, 404: null },
    rateLimit: { limit: 60, windowSeconds: 60 },
  },

  // ---- quests (Phase 02) ----
  {
    method: 'POST',
    path: '/v1/quests',
    tag: 'quests',
    summary: 'Draft a Quest (owner is the authenticated principal)',
    auth: ['MANAGE_OWN_QUESTS'],
    requiresVerifiedEmail: true,
    request: createQuestRequestSchema,
    // 409: the per-owner cap on Quests in a non-terminal state (QUEST_MAX_ACTIVE_PER_OWNER).
    responses: { 201: questDetailSchema, 400: null, 403: null, 409: null },
    rateLimit: { limit: 20, windowSeconds: 60 },
  },
  {
    method: 'GET',
    path: '/v1/quests',
    tag: 'quests',
    summary: 'Discover published public Quests (newest first, unranked)',
    auth: 'public',
    query: questListQuerySchema,
    responses: { 200: questListSchema },
    rateLimit: { limit: 60, windowSeconds: 60 },
  },
  {
    method: 'GET',
    path: '/v1/quests/mine',
    tag: 'quests',
    summary: "The caller's own Quests in every state",
    auth: ['MANAGE_OWN_QUESTS'],
    query: listPageQuerySchema,
    responses: { 200: questListSchema },
  },
  {
    method: 'GET',
    path: '/v1/quests/:questId',
    tag: 'quests',
    summary: 'Quest detail (404 when the caller may not know it exists)',
    auth: 'public',
    responses: { 200: questDetailSchema, 404: null },
    rateLimit: { limit: 60, windowSeconds: 60 },
  },
  {
    method: 'PUT',
    path: '/v1/quests/:questId',
    tag: 'quests',
    summary: 'Replace Quest content; a safety-relevant change unpublishes it',
    auth: ['MANAGE_OWN_QUESTS'],
    request: updateQuestRequestSchema,
    responses: { 200: questDetailSchema, 400: null, 404: null, 409: null },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/quests/:questId/assessment',
    tag: 'quests',
    summary: 'Request a safety assessment of the current content',
    auth: ['MANAGE_OWN_QUESTS'],
    responses: { 200: questAssessmentViewSchema, 404: null, 409: null },
    rateLimit: { limit: 10, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/quests/:questId/publish',
    tag: 'quests',
    summary: 'Publish a Quest (fails closed with machine-readable blockers)',
    auth: ['MANAGE_OWN_QUESTS'],
    requiresVerifiedEmail: true,
    request: publishQuestRequestSchema,
    responses: { 200: questDetailSchema, 404: null, 409: null },
    rateLimit: { limit: 10, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/quests/:questId/archive',
    tag: 'quests',
    summary: 'Archive a Quest and cancel its active attempts',
    auth: ['MANAGE_OWN_QUESTS'],
    request: archiveQuestRequestSchema,
    responses: { 200: questDetailSchema, 404: null, 409: null },
  },
  {
    method: 'GET',
    path: '/v1/quest-categories',
    tag: 'public',
    summary: 'Quest category catalogue',
    auth: 'public',
    responses: { 200: questCategoryListSchema },
    rateLimit: { limit: 60, windowSeconds: 60 },
  },

  // ---- participation (Phase 02) ----
  {
    method: 'POST',
    path: '/v1/quests/:questId/participation',
    tag: 'participation',
    summary: 'Accept a Quest (eligibility evaluated server-side)',
    auth: ['PARTICIPATE_IN_QUESTS'],
    request: acceptQuestRequestSchema,
    responses: { 201: participationViewSchema, 403: null, 404: null, 409: null },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'GET',
    path: '/v1/me/participations',
    tag: 'participation',
    summary: "The caller's own attempts",
    auth: ['PARTICIPATE_IN_QUESTS'],
    query: listPageQuerySchema,
    responses: { 200: participationListSchema },
  },
  {
    method: 'POST',
    path: '/v1/me/participations/:participationId/start',
    tag: 'participation',
    summary: 'Start an accepted attempt (opens the completion window)',
    auth: ['PARTICIPATE_IN_QUESTS'],
    responses: { 200: participationViewSchema, 404: null, 409: null },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/me/participations/:participationId/completion-request',
    tag: 'participation',
    summary: 'Declare completion (evidence and verification are later phases)',
    auth: ['PARTICIPATE_IN_QUESTS'],
    request: completionRequestSchema,
    responses: { 200: participationViewSchema, 404: null, 409: null },
    rateLimit: { limit: 30, windowSeconds: 60 },
  },
  {
    method: 'POST',
    path: '/v1/me/participations/:participationId/cancel',
    tag: 'participation',
    summary: 'Abandon an attempt',
    auth: ['PARTICIPATE_IN_QUESTS'],
    responses: { 200: participationViewSchema, 404: null, 409: null },
  },

  // ---- staff ----
  {
    method: 'GET',
    path: '/v1/admin/accounts/:accountId',
    tag: 'admin',
    summary: 'Support view of an account',
    auth: ['VIEW_USER_SUPPORT_PROFILE'],
    responses: { 200: accountSupportViewSchema, 404: null },
  },
  {
    method: 'POST',
    path: '/v1/admin/accounts/:accountId/suspend',
    tag: 'admin',
    summary: 'Suspend an account',
    auth: ['SANCTION_USER'],
    request: suspendAccountRequestSchema,
    responses: { 200: accountSupportViewSchema, 409: null },
  },
  {
    method: 'POST',
    path: '/v1/admin/accounts/:accountId/reinstate',
    tag: 'admin',
    summary: 'Reinstate a suspended account',
    auth: ['SANCTION_USER'],
    responses: { 200: accountSupportViewSchema, 409: null },
  },
  {
    method: 'POST',
    path: '/v1/admin/accounts/:accountId/roles',
    tag: 'admin',
    summary: 'Grant a staff role',
    auth: ['MANAGE_STAFF'],
    request: grantRoleRequestSchema,
    responses: { 200: accountSupportViewSchema },
  },
  {
    method: 'POST',
    path: '/v1/admin/accounts/:accountId/roles/revoke',
    tag: 'admin',
    summary: 'Revoke a staff role',
    auth: ['MANAGE_STAFF'],
    request: revokeRoleRequestSchema,
    responses: { 200: accountSupportViewSchema },
  },
  {
    method: 'GET',
    path: '/v1/admin/quests/:questId',
    tag: 'admin',
    summary: 'Support view of a Quest with its assessment history',
    auth: ['VIEW_QUEST_SUPPORT'],
    responses: { 200: questSupportViewSchema, 404: null },
  },
  {
    method: 'POST',
    path: '/v1/admin/quests/:questId/suspend',
    tag: 'admin',
    summary: 'Withdraw a Quest from visibility',
    auth: ['SANCTION_QUEST'],
    request: suspendQuestRequestSchema,
    responses: { 200: questSupportViewSchema, 404: null, 409: null },
  },
  {
    method: 'POST',
    path: '/v1/admin/quests/:questId/reinstate',
    tag: 'admin',
    summary: 'Return a suspended Quest to DRAFT',
    auth: ['SANCTION_QUEST'],
    responses: { 200: questSupportViewSchema, 404: null, 409: null },
  },
];
